# This is a basic workflow to help you get started with Actions

name: gh

# Controls when the workflow will run
on:
 
  push:
    paths:
      - ".github/workflows/gh.yml"

    
   
  
  workflow_dispatch:  #manual
  


jobs:
  cli:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - run: env
      - run: gh --version
      - run: gh auth status
      - run: gh repo list
      - run: gh issue list
      - run: gh workflow list
      - run: gh api /repos/:owner/:repo/actions/workflows

